apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-server
spec:
  selector:
    matchLabels:
      app: token-server
  replicas: 1
  template:
    metadata:
      labels:
        app: token-server
    spec:
      containers:
      - name: token-server
        image: commerceblockx/token-server:latest
        ports:
        - containerPort: 8001
        command: ["cargo", "run", "--bin", "token-server"]
        env:
        - name: PROCESSOR_URL
          value: "https://api.swiss-bitcoin-pay.ch"
        - name: API_KEY
          value: "684e8697137644bf9a97f6a5d2132349"
        - name: FEE
          value: "0.001"
        - name: DELAY
          value: "60"
        - name: CONNECTION_STRING
          value: "postgresql://postgres:password1@45.76.136.11/mercury_token2"
