services:

  bitcoind:
    image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
    user: root
    command: -regtest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth=user:63cf03615adebaa9356591f95b07ec7b$$920588e53f94798bda636acac1b6a77e10e3ee7fe57e414d62f3ee9e580cd27a -fallbackfee=0.0001 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "18443:18443"
    volumes:
      - bitcoin_data:/root/.bitcoin

  electrs:
    image: getumbrel/electrs:v0.9.4@sha256:b1590ac6cfb0e5b481c6a7af7f0626d76cbb91c63702b0f5c47e2829e9c37997
    user: root
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "regtest"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:18443"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:18444"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_SERVER_BANNER: "Umbrel Electrs"
    ports:
      - "50001:50001"
    volumes:
      - electrs-data:/data
      - bitcoin_data:/root/.bitcoin
    depends_on:
      - bitcoind

  alice:
    image: lightninglabs/lnd:v0.18.0-beta
    user: root
    hostname: lnd
    entrypoint: 
      - sh
      - -c
      - |
        mkdir -p /data/.lnd
        if [ ! -f "/data/.lnd/umbrel-lnd.conf" ]; then
          touch "/data/.lnd/umbrel-lnd.conf"
        fi
        lnd --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=user --bitcoind.rpcpass=pass --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --configfile=/data/.lnd/umbrel-lnd.conf
    ports:
      - "9735:9735" 
    volumes:
      - alice-data:/data/.lnd
    restart: unless-stopped
    environment:
      HOME: /data
    depends_on:
      - bitcoind

  bob:
    image: lightninglabs/lnd:v0.18.0-beta
    user: root
    hostname: lnd
    entrypoint: 
      - sh
      - -c
      - |
        mkdir -p /data/.lnd
        if [ ! -f "/data/.lnd/umbrel-lnd.conf" ]; then
          touch "/data/.lnd/umbrel-lnd.conf"
        fi
        lnd --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=user --bitcoind.rpcpass=pass --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --configfile=/data/.lnd/umbrel-lnd.conf
    ports:
      - "9736:9735" 
    volumes:
      - bob-data:/data/.lnd
    restart: unless-stopped
    environment:
      HOME: /data
    depends_on:
      - bitcoind

volumes:
  bitcoin_data:
  electrs-data:
  alice-data:
  bob-data:
