statechain_entity = "caqa7fv4wmmhj7owhmkdq23nfejxoibsi74qos2ggldbtg75u45g4uid.onion"
tor_proxy = ""socks5://127.0.0.1:9150"
electrum_server = "tcp://127.0.0.1:50001"
network = "signet"
fee_rate_tolerance = 5
database_file="wallet.db"