network = "testnet"
lockheight_init = 1000
lh_decrement = 10
batch_timeout = 120 # seconds
db_user = "postgres"
db_password = "postgres"
db_host = "localhost"
db_port = 5432
db_name = "mercury"

[[enclaves]]
url = "http://0.0.0.0:18080"
allow_deposit = true

[[enclaves]]
url = "http://0.0.0.0:18080"
allow_deposit = false

[[enclaves]]
url = "http://0.0.0.0:18080"
allow_deposit = true

[[enclaves]]
url = "http://0.0.0.0:18080"
allow_deposit = true

[[enclaves]]
url = "http://0.0.0.0:18080"
allow_deposit = true

# env var: ENCLAVES='[{"url": "http://0.0.0.0:18080", "allow_deposit": true}, {"url": "http://0.0.0.0:18080", "allow_deposit": false}]'
